const START=new Date("2026-10-16T08:00:00+05:30");
const KEY="koldiha_v4";
const ADMIN_PIN="2026";
const DRIVE_FOLDER="https://drive.google.com/drive/folders/1FHP8dYCxsWCzA7raGUX8VN6CekHAln_U?usp=sharing";
const DRIVE_ID="1FHP8dYCxsWCzA7raGUX8VN6CekHAln_U";
const seed={settings:{liveUrl:"",upi:"",qrUrl:"",bannerUrl:"",aarti:"07:00 PM • पंडाल",driveFolder:DRIVE_FOLDER,expense:0},events:[{day:"षष्ठी",title:"कलश स्थापना",when:"16 अक्तू • 08:00 AM"},{day:"सप्तमी",title:"प्रातः पूजा",when:"17 अक्तू"},{day:"अष्टमी",title:"संधि पूजा",when:"18–19 अक्तू"},{day:"नवमी",title:"हवन",when:"19 अक्तू"},{day:"दशमी",title:"विसर्जन",when:"20 अक्तू • 04:00 PM"}],announcements:[{title:"स्वागत",message:"ग्राम कोलडिहा दुर्गा पूजा 16–20 अक्तू 2026।",created:Date.now()}],donations:[],gallery:[],expenses:[]};
let db=load(),user=null,admin=sessionStorage.getItem("k_admin")==="1",cloud=false,fs=null,auth=null,lastAnn=Number(localStorage.getItem("k_last_ann")||0);
function load(){try{return Object.assign(JSON.parse(JSON.stringify(seed)),JSON.parse(localStorage.getItem(KEY)||"{}"));}catch(e){return JSON.parse(JSON.stringify(seed));}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(db));}
function toast(m){const t=document.getElementById("toast");if(!t)return;t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2400);}
function inr(n){return "₹"+Number(n||0).toLocaleString("en-IN");}
function uid(){return (auth&&auth.currentUser&&auth.currentUser.uid)||(user&&user.uid)||"";}
function uname(){return (user&&(user.displayName||user.email))||"";}
function ytId(url){if(!url)return"";const m=String(url).match(/(?:youtu\.be\/|v=|embed\/|live\/|shorts\/)([A-Za-z0-9_-]{11})/);return m?m[1]:"";}
function driveId(url){if(!url)return"";const s=String(url);const a=s.match(/\/file\/d\/([A-Za-z0-9_-]+)/);if(a)return a[1];const b=s.match(/[?&]id=([A-Za-z0-9_-]+)/);return b?b[1]:"";}
function folderId(url){const m=String(url||"").match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:DRIVE_ID;}
function mediaUrl(url){if(!url)return"";const id=driveId(url);return id?("https://drive.google.com/thumbnail?id="+id+"&sz=w1200"):url;}
function go(name){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("on",p.id==="p-"+name));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("on",b.dataset.p===name));if(name==="home")renderHome();if(name==="events")renderEvents();if(name==="live")renderLive();if(name==="donate")renderDon();if(name==="news")renderNews();if(name==="gallery")renderGal();if(name==="account")renderAcct();if(name==="admin")renderAdmin();if(name==="aarti")renderAarti();}
function tick(){const d=START-Date.now();const el=(id,v)=>{const n=document.getElementById(id);if(n)n.textContent=v;};if(d<=0){el("cdD","0");el("cdH","0");el("cdM","0");}else{el("cdD",Math.floor(d/86400000));el("cdH",Math.floor((d%86400000)/3600000));el("cdM",Math.floor((d%3600000)/60000));}const c=document.getElementById("clock");if(c){const n=new Date();c.textContent=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0");}}
function renderHome(){const img=document.getElementById("bannerImg");if(img&&db.settings.bannerUrl){img.src=mediaUrl(db.settings.bannerUrl);img.style.display="block";}const a=(db.announcements||[])[0];const t=document.getElementById("homeNewsT");if(t)t.textContent=a?(a.title+" — "+a.message):"अभी कोई नई सूचना नहीं।";const s=document.getElementById("syncMark");if(s)s.textContent=cloud?"क्लाउड":"लोकल";const newest=Math.max(0,...(db.announcements||[]).map(x=>x.created||0));const b=document.getElementById("bellBtn");if(b)b.classList.toggle("on",newest>lastAnn);}
function renderEvents(){const el=document.getElementById("eventList");if(el)el.innerHTML=(db.events||[]).map(e=>'<div class="card"><div class="meta">'+e.day+"</div><h3>"+e.title+"</h3><div class=\"meta\">"+(e.when||"")+"</div></div>").join("");}
function renderLive(){const box=document.getElementById("liveBox");if(!box)return;const id=ytId(db.settings.liveUrl);box.innerHTML=id?'<iframe class="player" src="https://www.youtube.com/embed/'+id+'?autoplay=1&mute=1" allow="autoplay;encrypted-media;picture-in-picture" allowfullscreen></iframe>':'<p class="meta">एडमिन YouTube लाइव लिंक पेस्ट करे।</p>';}
function renderAarti(){const e=document.getElementById("aartiMeta");if(e)e.textContent=db.settings.aarti||"07:00 PM";}
function mine(){const id=uid();const name=uname();return (db.donations||[]).filter(d=> (id&&d.uid===id) || (!id&&name&&d.name===name));}
function grouped(){const map={};(db.donations||[]).forEach(d=>{const k=d.uid&&d.uid!=="local"?d.uid:("n:"+d.name);if(!map[k])map[k]={name:d.name,uid:d.uid,amt:0,visible:true,photo:d.photo,date:d.date};map[k].amt+=Number(d.amt||0);map[k].visible=d.visible!==false;if(d.photo)map[k].photo=d.photo;map[k].date=d.date||map[k].date;});return Object.values(map).sort((a,b)=>b.amt-a.amt);}
function renderDon(){const inc=(db.donations||[]).reduce((s,x)=>s+Number(x.amt||0),0);const exp=Number(db.settings.expense||0)+(db.expenses||[]).reduce((s,x)=>s+Number(x.amt||0),0);const i=document.getElementById("inc");if(!i)return;i.textContent=inr(inc);document.getElementById("exp").textContent=inr(exp);document.getElementById("bal").textContent=inr(inc-exp);const my=mine().reduce((s,x)=>s+Number(x.amt||0),0);const ml=document.getElementById("myDonLine");if(ml)ml.textContent=user?("आपका कुल सहयोग: "+inr(my)+" — नयी राशि जोड़ने पर जुड़ जाएगी"):"पहले खाता बनाओ, फिर चंदा अपडेट हो";const qr=document.getElementById("qrImg");if(db.settings.qrUrl){qr.src=mediaUrl(db.settings.qrUrl);qr.style.display="block";}else qr.style.display="none";document.getElementById("upiLine").textContent=db.settings.upi?("UPI: "+db.settings.upi):"UPI ID एडमिन डाले";const dn=document.getElementById("dn");if(dn&&!dn.value&&uname())dn.value=uname();document.getElementById("donList").innerHTML=grouped().map(d=>{if(!d.visible)return '<div class="card"><b>सेवा मिल चुकी है</b></div>';const src=mediaUrl(d.photo);const ph=src?'<img class="avatar" src="'+src+'"/>':'<div class="avatar">'+(d.name||"स").charAt(0)+"</div>";return '<div class="card row">'+ph+'<div style="flex:1"><b>'+d.name+'</b><div class="meta">कुल सहयोग • '+(d.date||"")+'</div></div><div class="amt">'+inr(d.amt)+"</div></div>";}).join("");}
function renderNews(){lastAnn=Math.max(0,...(db.announcements||[]).map(x=>x.created||0));localStorage.setItem("k_last_ann",String(lastAnn));const b=document.getElementById("bellBtn");if(b)b.classList.remove("on");document.getElementById("newsList").innerHTML=(db.announcements||[]).map(a=>'<div class="card notice"><h3>'+a.title+"</h3><p>"+a.message+"</p></div>").join("");}
function renderGal(){const fid=folderId(db.settings.driveFolder||DRIVE_FOLDER);const fr=document.getElementById("driveFrame");if(fr)fr.src="https://drive.google.com/embeddedfolderview?id="+fid+"#grid";const op=document.getElementById("driveOpen");if(op)op.href=db.settings.driveFolder||DRIVE_FOLDER;const g=db.gallery||[];const el=document.getElementById("galGrid");if(el)el.innerHTML=g.map(u=>'<img src="'+mediaUrl(u.url||u)+'"/>').join("");}
function renderAcct(){const box=document.getElementById("acctBox");if(!box)return;if(user){const my=mine().reduce((s,x)=>s+Number(x.amt||0),0);box.innerHTML="<p><b>"+(uname())+"</b></p><p class=\"meta\">"+(user.email||"")+"</p>"+(admin?'<span class="badge">समिति एडमिन</span>':'<span class="badge">श्रद्धालु</span>')+"<p>आपका चंदा: <b>"+inr(my)+"</b></p><button class=\"btn\" onclick=\"go('donate')\">चंदा जोड़ो</button><button class=\"btn ghost\" onclick=\"logout()\">लॉग आउट</button>";return;}box.innerHTML='<p class="meta">श्रद्धालु खाता — चंदा अपडेट करने के लिए</p><label class="lab">नाम</label><input id="nm"/><label class="lab">ईमेल</label><input id="em" type="email"/><label class="lab">पासवर्ड</label><input id="pw" type="password"/><button class="btn" onclick="doReg()">श्रद्धालु खाता बनाओ</button><button class="btn ghost" onclick="doLogin()">लॉगिन</button><hr/><p class="meta">समिति एडमिन के लिए पहले लॉगिन, फिर एडमिन पेज पर पिन 2026 डालो।</p>';}
function closeAdmin(){admin=false;sessionStorage.removeItem("k_admin");renderAdmin();}
function renderAdmin(){const gate=document.getElementById("adminGate");const tools=document.getElementById("adminTools");if(!gate)return;if(admin){gate.innerHTML='<p>समिति पैनल चालू <span class="badge">ADMIN</span></p><button class="btn ghost" onclick="closeAdmin()">बंद</button>';tools.style.display="block";const map={liveUrl:"liveUrl",upiId:"upi",aartiIn:"aarti",qrUrl:"qrUrl",banUrl:"bannerUrl",driveFolder:"driveFolder"};Object.keys(map).forEach(id=>{const el=document.getElementById(id);if(el)el.value=db.settings[map[id]]||"";});return;}tools.style.display="none";gate.innerHTML=(user?'<p class="meta">लॉगिन है: '+uname()+'</p>':'<p class="meta">पहले खाता से लॉगिन करो</p>')+'<input id="pin" inputmode="numeric" placeholder="एडमिन पिन 2026"/><button class="btn" onclick="tryAdmin()">समिति लॉगिन</button>';}
function tryAdmin(){if((document.getElementById("pin")||{}).value!==ADMIN_PIN)return toast("पिन गलत");if(!user)return toast("पहले खाता लॉगिन करो");admin=true;sessionStorage.setItem("k_admin","1");promoteAdmin();renderAdmin();toast("एडमिन चालू");}
async function promoteAdmin(){if(cloud&&auth&&auth.currentUser)await fs.collection("users").doc(auth.currentUser.uid).set({role:"admin",email:auth.currentUser.email,name:uname()},{merge:true});}
function logout(){user=null;admin=false;sessionStorage.removeItem("k_admin");if(auth)auth.signOut();renderAcct();toast("लॉग आउट");}
function fbErr(e){const c=e&&e.code||"";if(c.indexOf("unauthorized")>=0||c.indexOf("unauthorized-continue-uri")>=0)return "GitHub domain Firebase में जोड़ो";if(c==="auth/operation-not-allowed")return "Email login चालू करो";if(c==="auth/email-already-in-use")return "ईमेल पहले से लॉगिन करो";if(c==="auth/invalid-credential"||c==="auth/wrong-password")return "ईमेल/पासवर्ड गलत";if(c==="auth/weak-password")return "पासवर्ड 6 अक्षर से ज्यादा";return "फेल: "+(c||e.message||"error");}
async function doReg(){const name=document.getElementById("nm").value.trim();const em=document.getElementById("em").value.trim();const pw=document.getElementById("pw").value;if(!name||!em||!pw)return toast("नाम, ईमेल, पासवर्ड लिखें");if(!cloud||!auth)return toast("Firebase क्लाउड बंद");try{const cred=await auth.createUserWithEmailAndPassword(em,pw);await cred.user.updateProfile({displayName:name});await fs.collection("users").doc(cred.user.uid).set({name,email:em,role:"user",created:Date.now()});toast("खाता बन गया");}catch(e){toast(fbErr(e));}}
async function doLogin(){const em=document.getElementById("em").value.trim();const pw=document.getElementById("pw").value;if(!em||!pw)return toast("ईमेल-पासवर्ड");if(!cloud||!auth)return toast("Firebase बंद");try{await auth.signInWithEmailAndPassword(em,pw);toast("लॉगिन हो गया");}catch(e){toast(fbErr(e));}}
async function addDon(){if(!user){toast("पहले खाता लॉगिन करो");return go("account");}const name=document.getElementById("dn").value.trim()||uname();const amt=Number(document.getElementById("da").value);const visible=document.getElementById("dvis").checked;const photo=document.getElementById("dpUrl").value.trim();if(!amt||amt<=0)return toast("राशि लिखें");const row={name,amt,visible,photo,date:new Date().toISOString().slice(0,10),created:Date.now(),uid:uid()||"local"};if(cloud&&fs)await fs.collection("donations").add(row);else{db.donations.push(row);saveLocal();}document.getElementById("da").value="";renderDon();toast("चंदा जुड़ गई • आपका कुल "+inr(mine().reduce((s,x)=>s+Number(x.amt||0),0)));}
function payUPI(){const amt=Number((document.getElementById("da")||{}).value||0);const pa=db.settings.upi||"";if(!pa)return toast("एडमिन पहले UPI ID डाले");const url="upi://pay?pa="+encodeURIComponent(pa)+"&pn="+encodeURIComponent("ग्राम कोलडिहा दुर्गा पूजा")+(amt?("&am="+amt):"")+"&cu=INR";location.href=url;}
async function saveSetting(patch){db.settings=Object.assign({},db.settings,patch);saveLocal();if(cloud&&fs)await fs.collection("settings").doc("main").set(db.settings,{merge:true});}
async function saveLive(){await saveSetting({liveUrl:document.getElementById("liveUrl").value.trim()});toast("लाइव सेव");renderLive();}
async function saveAarti(){await saveSetting({aarti:document.getElementById("aartiIn").value.trim()});toast("आरती सेव");}
async function saveQr(){await saveSetting({upi:document.getElementById("upiId").value.trim(),qrUrl:document.getElementById("qrUrl").value.trim()});toast("UPI/QR सेव");renderDon();}
async function saveBanner(){await saveSetting({bannerUrl:document.getElementById("banUrl").value.trim()});toast("बैनर सेव");renderHome();}
async function saveDriveFolder(){const link=document.getElementById("driveFolder").value.trim()||DRIVE_FOLDER;await saveSetting({driveFolder:link});toast("फ़ोल्डर सेव");renderGal();}
async function addExp(){const amt=Number(document.getElementById("expAmt").value);const note=document.getElementById("expNote").value.trim();if(!amt)return toast("खर्च राशि");const row={amt,note,created:Date.now()};if(cloud&&fs)await fs.collection("expenses").add(row);else{db.expenses.push(row);saveLocal();}await saveSetting({expense:Number(db.settings.expense||0)+amt});toast("खर्च जुड़ा");renderDon();}
async function saveAnnounce(){const title=document.getElementById("anTitle").value.trim();const message=document.getElementById("anMsg").value.trim();if(!title||!message)return toast("लिखें");const row={title,message,created:Date.now()};if(cloud&&fs)await fs.collection("announcements").add(row);else{db.announcements.unshift(row);saveLocal();}ping(title,message);toast("सूचना");renderHome();renderNews();}
async function saveEvent(){const row={day:document.getElementById("evDay").value.trim(),title:document.getElementById("evTitle").value.trim(),when:document.getElementById("evWhen").value.trim()};if(!row.title)return toast("कार्यक्रम");if(cloud&&fs)await fs.collection("events").add(row);else{db.events.push(row);saveLocal();}toast("सेव");renderEvents();}
function ping(title,body){if("Notification"in window&&Notification.permission==="granted"){try{new Notification(title,{body,tag:"koldiha"});}catch(e){}}}
function askNotify(){if(!("Notification"in window))return toast("नहीं");Notification.requestPermission().then(p=>toast(p==="granted"?"चालू":"बंद"));}
async function initFb(){if(!window.FIREBASE_READY||!window.FIREBASE_READY()||!window.firebase)return;try{firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();fs=firebase.firestore();try{await fs.enablePersistence({synchronizeTabs:true});}catch(e){}cloud=true;document.getElementById("syncMark").textContent="क्लाउड";auth.onAuthStateChanged(async u=>{user=u;if(u){try{const snap=await fs.collection("users").doc(u.uid).get();if(snap.exists&&snap.data().role==="admin"){admin=true;sessionStorage.setItem("k_admin","1");}}catch(e){}}if(document.querySelector("#p-account.on"))renderAcct();if(document.querySelector("#p-donate.on"))renderDon();});listen("settings",docs=>{if(docs[0]){db.settings=Object.assign(db.settings,docs[0]);saveLocal();renderHome();renderLive();renderDon();renderAarti();renderGal();}});listen("events",docs=>{if(docs.length)db.events=docs;});listen("announcements",docs=>{if(!docs.length)return;const old=lastAnn;db.announcements=docs.sort((a,b)=>(b.created||0)-(a.created||0));saveLocal();const n=db.announcements[0];if(n&&n.created>old)ping(n.title,n.message);renderHome();});listen("donations",docs=>{db.donations=docs;saveLocal();renderDon();});listen("expenses",docs=>{if(docs.length){db.expenses=docs;saveLocal();renderDon();}});}catch(e){cloud=false;}}
function listen(col,cb){fs.collection(col).onSnapshot(qs=>cb(qs.docs.map(d=>Object.assign({id:d.id},d.data()))),()=>{});}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
setTimeout(()=>{const s=document.getElementById("splash");if(s)s.classList.add("hide");},1500);
tick();setInterval(tick,30000);renderHome();renderGal();initFb();
