const START=new Date("2026-10-16T08:00:00+05:30");
const KEY="koldiha_v2";
const ADMIN_PIN="2026";
const seed={settings:{liveUrl:"",upi:"",qrUrl:"",bannerUrl:"",aarti:"07:00 PM • पंडाल"},events:[{day:"षष्ठी",title:"कलश स्थापना",when:"16 अक्तू • 08:00 AM"},{day:"सप्तमी",title:"प्रातः पूजा",when:"17 अक्तू • 09:00 AM"},{day:"अष्टमी",title:"संधि पूजा",when:"18–19 अक्तू"},{day:"नवमी",title:"हवन",when:"19 अक्तू"},{day:"दशमी",title:"विसर्जन",when:"20 अक्तू • 04:00 PM"}],announcements:[{title:"स्वागत",message:"ग्राम कोलडिहा दुर्गा पूजा 16–20 अक्तू 2026।",created:Date.now()}],donations:[],gallery:[]};
let db=load(),user=null,admin=sessionStorage.getItem("k_admin")==="1",cloud=false,fs=null,st=null,auth=null,lastAnn=Number(localStorage.getItem("k_last_ann")||0);
function load(){try{return Object.assign(JSON.parse(JSON.stringify(seed)),JSON.parse(localStorage.getItem(KEY)||"{}"));}catch(e){return JSON.parse(JSON.stringify(seed));}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(db));}
function toast(m){const t=document.getElementById("toast");t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",2200);}
function inr(n){return "₹"+Number(n||0).toLocaleString("en-IN");}
function ytId(url){if(!url)return"";const m=String(url).match(/(?:youtu\.be\/|v=|embed\/|live\/|shorts\/)([A-Za-z0-9_-]{11})/);return m?m[1]:(/^[A-Za-z0-9_-]{11}$/.test(url)?url:"");}
function go(name){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("on",p.id==="p-"+name));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("on",b.dataset.p===name));if(name==="home")renderHome();if(name==="events")renderEvents();if(name==="live")renderLive();if(name==="donate")renderDon();if(name==="news")renderNews();if(name==="gallery")renderGal();if(name==="account")renderAcct();if(name==="admin")renderAdmin();if(name==="aarti")renderAarti();}
function tick(){const d=START-Date.now();const el=(id,v)=>{const n=document.getElementById(id);if(n)n.textContent=v;};if(d<=0){el("cdD","0");el("cdH","0");el("cdM","0");}else{el("cdD",Math.floor(d/86400000));el("cdH",Math.floor((d%86400000)/3600000));el("cdM",Math.floor((d%3600000)/60000));}const c=document.getElementById("clock");if(c){const n=new Date();c.textContent=String(n.getHours()).padStart(2,"0")+":"+String(n.getMinutes()).padStart(2,"0");}}
function renderHome(){const img=document.getElementById("bannerImg");if(img&&db.settings.bannerUrl){img.src=db.settings.bannerUrl;img.style.display="block";}const a=(db.announcements||[])[0];const t=document.getElementById("homeNewsT");if(t)t.textContent=a?(a.title+" — "+a.message):"अभी कोई नई सूचना नहीं।";const s=document.getElementById("syncMark");if(s)s.textContent=cloud?"क्लाउड":"लोकल";const newest=Math.max(0,...(db.announcements||[]).map(x=>x.created||0));const b=document.getElementById("bellBtn");if(b)b.classList.toggle("on",newest>lastAnn);}
function renderEvents(){document.getElementById("eventList").innerHTML=(db.events||[]).map(e=>'<div class="card"><div class="meta">'+e.day+"</div><h3>"+e.title+"</h3><div class=\"meta\">"+(e.when||"")+"</div></div>").join("")||'<div class="card">खाली</div>';}
function renderLive(){const id=ytId(db.settings.liveUrl);const box=document.getElementById("liveBox");if(!id){box.innerHTML='<p class="meta">एडमिन YouTube लिंक पेस्ट करे।</p>';return;}box.innerHTML='<iframe class="player" src="https://www.youtube.com/embed/'+id+'?autoplay=1&mute=1" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe><p class="meta">🔴 लाइव</p>';}
function renderAarti(){const e=document.getElementById("aartiMeta");if(e)e.textContent=db.settings.aarti||"07:00 PM";}
function renderDon(){const inc=(db.donations||[]).reduce((s,x)=>s+Number(x.amt||0),0);const i=document.getElementById("inc");if(!i)return;i.textContent=inr(inc);document.getElementById("exp").textContent=inr(0);document.getElementById("bal").textContent=inr(inc);const qr=document.getElementById("qrImg");if(db.settings.qrUrl){qr.src=db.settings.qrUrl;qr.style.display="block";}else qr.style.display="none";document.getElementById("upiLine").textContent=db.settings.upi?("UPI: "+db.settings.upi):"";document.getElementById("donList").innerHTML=(db.donations||[]).slice().reverse().map(d=>{if(d.visible===false)return '<div class="card"><b>सेवा मिल चुकी है</b><div class="meta">नाम छिपाया गया</div></div>';const ph=d.photo?'<img class="avatar" src="'+d.photo+'"/>':'<div class="avatar">'+(d.name||"स").charAt(0)+"</div>";return '<div class="card row">'+ph+'<div style="flex:1"><b>'+d.name+'</b><div class="meta">'+(d.date||"")+'</div></div><div class="amt">'+inr(d.amt)+"</div></div>";}).join("");}
function renderNews(){lastAnn=Math.max(0,...(db.announcements||[]).map(x=>x.created||0));localStorage.setItem("k_last_ann",String(lastAnn));const b=document.getElementById("bellBtn");if(b)b.classList.remove("on");document.getElementById("newsList").innerHTML=(db.announcements||[]).map(a=>'<div class="card notice"><h3>'+a.title+"</h3><p>"+a.message+'</p></div>').join("");}
function renderGal(){const g=db.gallery||[];document.getElementById("galGrid").innerHTML=g.length?g.map(u=>'<img src="'+(u.url||u)+'"/>').join(""):"<div>📷</div><div>🌺</div><div>🪔</div>";}
function renderAcct(){const box=document.getElementById("acctBox");if(user){box.innerHTML="<p><b>"+(user.displayName||user.email)+"</b></p>"+(admin?'<span class="badge">एडमिन</span>':'')+'<button class="btn ghost" onclick="logout()">लॉग आउट</button>';return;}box.innerHTML='<label class="lab">नाम</label><input id="nm"/><label class="lab">ईमेल</label><input id="em" type="email"/><label class="lab">पासवर्ड</label><input id="pw" type="password"/><button class="btn" onclick="doReg()">खाता बनाओ</button><button class="btn ghost" onclick="doLogin()">लॉगिन</button>';}
function closeAdmin(){admin=false;sessionStorage.removeItem("k_admin");renderAdmin();}
function renderAdmin(){const gate=document.getElementById("adminGate");const tools=document.getElementById("adminTools");if(!gate)return;if(admin){gate.innerHTML='<p>एडमिन चालू <span class="badge">OK</span></p><button class="btn ghost" onclick="closeAdmin()">बंद</button>';tools.style.display="block";document.getElementById("liveUrl").value=db.settings.liveUrl||"";document.getElementById("upiId").value=db.settings.upi||"";document.getElementById("aartiIn").value=db.settings.aarti||"";return;}tools.style.display="none";gate.innerHTML='<p class="meta">पिन 2026</p><input id="pin" inputmode="numeric" placeholder="पिन"/><button class="btn" onclick="tryAdmin()">एडमिन खोलो</button>';}
function tryAdmin(){if((document.getElementById("pin")||{}).value===ADMIN_PIN){admin=true;sessionStorage.setItem("k_admin","1");promoteAdmin();renderAdmin();toast("एडमिन चालू");}else toast("पिन गलत");}
async function promoteAdmin(){if(cloud&&auth&&auth.currentUser)await fs.collection("users").doc(auth.currentUser.uid).set({role:"admin",email:auth.currentUser.email},{merge:true});}
function logout(){user=null;admin=false;sessionStorage.removeItem("k_admin");if(auth)auth.signOut();renderAcct();toast("लॉग आउट");}
async function doReg(){const name=document.getElementById("nm").value.trim();const em=document.getElementById("em").value.trim();const pw=document.getElementById("pw").value;if(!name)return toast("नाम लिखें");if(cloud&&auth&&em&&pw){try{const cred=await auth.createUserWithEmailAndPassword(em,pw);await cred.user.updateProfile({displayName:name});await fs.collection("users").doc(cred.user.uid).set({name,email:em,role:"user",created:Date.now()});toast("खाता बन गया");}catch(e){toast("खाता नहीं बना");}return;}user={displayName:name,email:em||"local"};renderAcct();toast("लोकल खाता");}
async function doLogin(){const em=document.getElementById("em").value.trim();const pw=document.getElementById("pw").value;if(cloud&&auth&&em&&pw){try{await auth.signInWithEmailAndPassword(em,pw);toast("लॉगिन");}catch(e){toast("लॉगिन नहीं");}return;}toast("Firebase जोड़ो");}
function fileToData(file){return new Promise(res=>{if(!file)return res("");const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file);});}
async function upload(path,file){if(!file)return"";if(cloud&&st){const ref=st.ref().child(path+"/"+Date.now()+"-"+file.name);await ref.put(file);return await ref.getDownloadURL();}return await fileToData(file);}
async function addDon(){const name=document.getElementById("dn").value.trim();const amt=Number(document.getElementById("da").value);const visible=document.getElementById("dvis").checked;if(!name||!amt)return toast("नाम और राशि");const photo=await upload("donations",document.getElementById("dp").files[0]);const row={name,amt,visible,photo,date:new Date().toISOString().slice(0,10),created:Date.now(),uid:(auth&&auth.currentUser&&auth.currentUser.uid)||"local"};if(cloud&&fs)await fs.collection("donations").add(row);else{db.donations.push(row);saveLocal();}document.getElementById("dn").value="";document.getElementById("da").value="";renderDon();toast("धन्यवाद");}
async function saveSetting(patch){db.settings=Object.assign({},db.settings,patch);saveLocal();if(cloud&&fs)await fs.collection("settings").doc("main").set(db.settings,{merge:true});}
async function saveLive(){await saveSetting({liveUrl:document.getElementById("liveUrl").value.trim()});toast("लाइव सेव");renderLive();}
async function saveAarti(){await saveSetting({aarti:document.getElementById("aartiIn").value.trim()});toast("आरती सेव");}
async function saveQr(){const upi=document.getElementById("upiId").value.trim();const url=await upload("qr",document.getElementById("qrFile").files[0]);await saveSetting({upi,qrUrl:url||db.settings.qrUrl});toast("QR सेव");renderDon();}
async function saveBanner(){const url=await upload("banner",document.getElementById("banFile").files[0]);if(!url)return toast("फोटो चुनो");await saveSetting({bannerUrl:url});toast("बैनर");renderHome();}
async function saveGallery(){const url=await upload("gallery",document.getElementById("galFile").files[0]);if(!url)return toast("फोटो चुनो");const row={url,created:Date.now()};if(cloud&&fs)await fs.collection("gallery").add(row);else{db.gallery.push(row);saveLocal();}toast("गैलरी");renderGal();}
async function saveAnnounce(){const title=document.getElementById("anTitle").value.trim();const message=document.getElementById("anMsg").value.trim();if(!title||!message)return toast("लिखें");const row={title,message,created:Date.now()};if(cloud&&fs)await fs.collection("announcements").add(row);else{db.announcements.unshift(row);saveLocal();}ping(title,message);toast("सूचना गई");renderHome();renderNews();}
async function saveEvent(){const row={day:document.getElementById("evDay").value.trim(),title:document.getElementById("evTitle").value.trim(),when:document.getElementById("evWhen").value.trim()};if(!row.title)return toast("कार्यक्रम लिखें");if(cloud&&fs)await fs.collection("events").add(row);else{db.events.push(row);saveLocal();}toast("सेव");renderEvents();}
function ping(title,body){if("Notification"in window&&Notification.permission==="granted"){try{new Notification(title,{body,tag:"koldiha"});}catch(e){}}}
function askNotify(){if(!("Notification"in window))return toast("नहीं");Notification.requestPermission().then(p=>toast(p==="granted"?"नोटिफ़िकेशन चालू":"मना नहीं"));}
async function initFb(){if(!window.FIREBASE_READY||!window.FIREBASE_READY()||!window.firebase)return;try{firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();fs=firebase.firestore();st=firebase.storage();try{await fs.enablePersistence({synchronizeTabs:true});}catch(e){}cloud=true;document.getElementById("syncMark").textContent="क्लाउड";auth.onAuthStateChanged(async u=>{user=u;if(u){const snap=await fs.collection("users").doc(u.uid).get();if(snap.exists&&snap.data().role==="admin"){admin=true;sessionStorage.setItem("k_admin","1");}}});listen("settings",docs=>{if(docs[0]){db.settings=Object.assign(db.settings,docs[0]);saveLocal();renderHome();renderLive();renderDon();renderAarti();}});listen("events",docs=>{if(docs.length)db.events=docs;saveLocal();});listen("announcements",docs=>{const old=lastAnn;db.announcements=docs.sort((a,b)=>(b.created||0)-(a.created||0));saveLocal();const n=db.announcements[0];if(n&&n.created>old)ping(n.title,n.message);renderHome();});listen("donations",docs=>{db.donations=docs;saveLocal();});listen("gallery",docs=>{db.gallery=docs;saveLocal();});}catch(e){cloud=false;}}
function listen(col,cb){fs.collection(col).onSnapshot(qs=>cb(qs.docs.map(d=>Object.assign({id:d.id},d.data()))));}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
setTimeout(()=>{const s=document.getElementById("splash");if(s)s.classList.add("hide");},1600);
tick();setInterval(tick,30000);renderHome();initFb();
